version: '3.8'

services:
  app:
    container_name: e-commerce
    build: .
    ports:
      - "5713:5713"
    depends_on:
      - mongo_db
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/e-commerce  # ใช้ชื่อ service 'mongo_db' แทน '127.0.0.1'

  mongo_db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: